# Generated by Django 6.0.3 on 2026-04-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
