# Generated by Django 6.0.3 on 2026-03-27 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aulas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_registro', models.DateTimeField(auto_now_add=True)),
                ('ip_registrado', models.GenericIPAddressField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('presente', 'Presente'), ('negado', 'Negado'), ('fora_do_raio', 'Fora do Raio'), ('rede_invalida', 'Rede Inválida')], default='presente', max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='usuarios.aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='aulas.aula')),
            ],
            options={
                'verbose_name': 'Presença',
                'verbose_name_plural': 'Presenças',
                'ordering': ['-horario_registro'],
                'unique_together': {('aluno', 'aula')},
            },
        ),
    ]
