# Generated by Django 6.0.3 on 2026-04-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedePermitida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('cidr', models.CharField(help_text='Notação CIDR. Ex: 200.129.128.0/17 ou 177.20.147.50/32', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rede Permitida',
                'verbose_name_plural': 'Redes Permitidas',
            },
        ),
    ]
